Group8
allegheny-computer-science-203-s2021/CodeOfConduct pull request #13
Opened 2021-03-03 20:56 UTC by RyanHiltyAllegheny

Here is the Group8 pull request for the Code of Conduct form. We feel we have completed our work for this section and it is ready to be merged with the main branch!

2021-03-03 21:05 UTC, corlettim requested changes
Make sure that all of your bullet points are equally spaced throughout the section. For example, some have a space between them and others do not. They should be formatted the same.

2021-03-03 21:06 UTC, corlettim commented
Also please make sure to resolve the conflicts with the main branch :)

2021-03-03 21:15 UTC, RyanHiltyAllegheny commented
I committed once again to make a few changes to the document, please specify what is conflicting with main if that issue continues to occur. Thanks!

2021-03-03 21:22 UTC, enpuyou commented
> I committed once again to make a few changes to the document, please specify what is conflicting with main if that issue continues to occur. Thanks!

@RyanHiltyAllegheny I think there are merge conflicts between this branch and main in the `conduct.md` file. You would be able to see the specific conflicts once you click on the `Resolve conflicts` button

2021-03-03 21:35 UTC, corlettim requested changes
You still have some linting errors so make sure to fix those

2021-03-03 21:36 UTC, noorbuchi requested changes

2021-03-03 21:36 UTC, noorbuchi commented on conduct.md
> +
Please remove these black lines to resolve linting error

2021-03-03 21:39 UTC, corlettim approved these changes, later dismissed

2021-03-03 21:43 UTC, Mai1902 commented
I have just solved the linting issue, please review it again. Thank you so much!

2021-03-03 21:43 UTC, corlettim commented
Everything looks good! Please make sure to fix the conflicts with main branch and you should be good to go

2021-03-03 21:44 UTC, noorbuchi commented
Please resolve merge conflicts with main branch. Once that's done, I'll review and you should be good to merge once you get enough approvals.

2021-03-03 21:52 UTC, noorbuchi approved these changes

2021-03-03 21:53 UTC, enpuyou approved these changes
The change looks good! Thanks!

2021-03-04 02:17 UTC, corlettim approved these changes

2021-03-04 02:26 UTC, merged