Group 6 postmortems
allegheny-computer-science-203-s2021/CodeOfConduct pull request #14
Opened 2021-03-04 18:44 UTC by BaileyMatrascia

2021-03-04 18:49 UTC, jjumadinova requested changes
Please merge the latest changes from main into this branch. If you scroll to the bottom, there is an option to do so.

2021-03-04 19:22 UTC, noorbuchi requested changes
Please include a description of the changes introduced in this PR and why you think they're necessary. Additionally, merge conflicts should be resolved before this PR can be merged. Thank you!

2021-03-05 19:58 UTC, antlet commented
This PR includes 3 spacing issues that were fixed.

2021-03-06 23:12 UTC, enpuyou approved these changes

2021-03-07 14:37 UTC, munzekm approved these changes

2021-03-07 19:18 UTC, noorbuchi approved these changes

2021-03-07 19:19 UTC, merged