Communication Section
allegheny-computer-science-203-s2021/CodeOfConduct pull request #9
Opened 2021-02-26 00:05 UTC by PaigeCD

This is Group 3's addition to the Communication section of the Code of Conduct. We're hoping to merge this so others who wish to add to this section can do so.

2021-02-26 02:26 UTC, noorbuchi requested changes
Hello! Thank you for your work on this PR, I added some change requests that should be addressed before merging this PR. Can you also please explain why all bullet points in the document were changed from `*` to `-`? Both of these notations serve the same purpose. Changing them can create unnecessary conflicts so I strongly encourage you to address that.

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +
Extra space is not needed between list items, please remove this to stay consistent with other sections

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
No extra space is needed here either

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +    - Bargain for more time to complete assignments.
Please make sure to communicate these changes to the Deadlines group, they are responsible for this section and they should be okay with your additions.

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +
Extra space is not needed here either

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +    - Use appropriate softwares for electronic communication.
I think it's good to be specific here. What method(s) of communication should the team use? Slack, GitHub Issue Trackers, email, all of them?

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +    - Make fun of other peoples contributions.
While I definitely think that making fun of other peoples' contributions is unacceptable, I don't think this point belongs in the communication section. You could also combine it with the inappropriate use of communication platforms and identify how that looks like.

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +
Extra space is not needed between list items, please remove this to stay consistent with other sections

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +
Another extra space

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +
Extra empty line should be removed

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +    - Thoroughly consider all feedback regardless of how it may initially seem.
Please remove empty lines from this section

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +
Empty line

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +    - Thoroughly consider all feedback regardless of how it may initially seem.
Please let the group responsible for postmortems know about these changes. Additionally, you should keep the `TODO` at the bottom of the list until the group responsible finalizes their contribution

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +_Infractions shall be imposed at three different levels of severity:_
Can you please explain the purpose of this change. It could potentially introduce unnecessary inconsistency with other branches.

2021-02-26 02:26 UTC, noorbuchi commented on conduct.md
> +Nate Angus
Please make sure to add the names of all group members. Additionally, the `TODO` section should be kept until other groups have also added their names

2021-02-26 02:30 UTC, noorbuchi commented
It's also not advisable to have someone who worked on the PR also be a reviewer. So please make sure to request the review of someone who hasn't contributed to this specific PR, it should preferably be a TL

2021-02-26 15:52 UTC, PaigeCD reviewed
In this commit I attempted to address a few concerns raised by Noor. In this commit I:
- Removed many empty lines
- Temporarily removed additions (with permission) to other sections so that they can be reviewed later
- Changed all - to * for consistency with main
- Made a specification in Communication requested by Noor
- Added punctuation to to Communication for consistency
- Put the TODO for adding names back
- Added my name to the file

2021-02-26 16:29 UTC, noorbuchi requested changes
Thank you for addressing the changes I requested! Please feel free to resolve the comments if the changes were implemented. I also made a couple of other requests in this review. Finally, there are merge conflicts between this and the main branch that need to be resolved before merging this PR.

2021-02-26 16:29 UTC, noorbuchi commented on conduct.md
> +_Infractions shall be imposed at three different levels of severity:_
Please don't forget to address this request

2021-02-26 16:29 UTC, noorbuchi commented on conduct.md
> +Paige Downey
I believe that there is a missing name that contributed to this PR but has not been added to the list

2021-02-26 16:36 UTC, corlettim commented
Great work so far! After taking a look at Noor's comments, please make sure you resolve the merge conflicts.

2021-02-26 16:37 UTC, corlettim requested changes
Great work so far! After taking a look at Noor's comments, please make sure you resolve the merge conflicts.

2021-02-27 01:50 UTC, noorbuchi submitted a review, later dismissed
I think this looks good! You've addressed all the requested changes. Please wait until this PR gets the needed approvals before merging.

2021-02-27 22:10 UTC, noorbuchi approved these changes, later dismissed

2021-02-27 22:11 UTC, corlettim approved these changes, later dismissed

2021-03-02 22:26 UTC, PaigeCD commented on conduct.md
> +
These extra spaces need removed again

2021-03-02 22:30 UTC, PaigeCD reviewed
It looks like you may have forgotten to pull before pushing this and some things have gotten undone.

2021-03-03 18:57 UTC, enpuyou requested changes
@PaigeCD It seems like the section your group contributed still has some markdown linting errors raised in Github Action. Make sure to resolve those before the PR could be merged.

2021-03-03 20:29 UTC, enpuyou approved these changes, later dismissed

2021-03-03 20:29 UTC, enpuyou commented on conduct.md
I think it would be best to preserve the original text for Level II, while having what your group has proposed here for the action.

2021-03-03 20:33 UTC, corlettim requested changes
Everything is coming together really well! Please make sure to fix the linting errors that you are now facing

2021-03-03 20:51 UTC, jjumadinova approved these changes, later dismissed

2021-03-03 20:58 UTC, corlettim requested changes

2021-03-03 20:58 UTC, corlettim commented on conduct.md
>      * :heavy_exclamation_mark: TODO: add items in the U category for attendance.
Make sure to remove your TODO statements

2021-03-03 20:58 UTC, corlettim commented on conduct.md
>      * :heavy_exclamation_mark: TODO: add any additional items in the U category for the postmortems.
Make sure to remove this TODO

2021-03-03 20:58 UTC, corlettim commented on conduct.md
>      * :heavy_exclamation_mark: TODO: add any additional items in the A category for the conflicts.
remove this please :)

2021-03-03 21:29 UTC, corlettim requested changes

2021-03-03 21:29 UTC, corlettim commented on conduct.md
> +    * Allow other group members to have an equal say in decisions.
I think you meant to put this under the shall not section but it is showing up in the shall section. I may be seeing it wrong but double check this is in the right spot.

2021-03-03 21:37 UTC, corlettim requested changes

2021-03-03 21:37 UTC, corlettim commented on conduct.md
> +    * Primarily discuss conflicts and issues with classmates with outside classmates and friends rather than with those they wish to resolve them with.
I think this needs be reworded. It is a little repetitive with "classmates" and "outside classmates"

2021-03-03 21:47 UTC, corlettim commented
Please make sure to resolve the conflicts with main branch and then you should be good to go

2021-03-03 22:00 UTC, enpuyou approved these changes, later dismissed
Thanks for addressing all the raised issues! I think the PR is good to go.

2021-03-04 02:15 UTC, corlettim approved these changes, later dismissed

2021-03-04 02:45 UTC, noorbuchi approved these changes, later dismissed
Everything looks good! Please resolve merge conflicts with `main` and we should be ready to merge your PR.

2021-03-04 02:59 UTC, corlettim requested changes

2021-03-04 02:59 UTC, corlettim commented on conduct.md
> +    * Share constructive criticism of others opinions before making a final decision as a group.
I think these 3 points need to be under "shall not" instead of "shall".

2021-03-04 03:03 UTC, noorbuchi requested changes
Overall everything looks great! I just noticed two small issues that should be addressed.

2021-03-04 03:03 UTC, noorbuchi commented on conduct.md
> +    * Share constructive criticism of others opinions before making a final decision as a group.
I think these should be in the unacceptable conduct section instead

2021-03-04 03:03 UTC, noorbuchi commented on conduct.md
> +
I think that `Teamwork` is a level above `Participation`, `Decisions`, etc.. So the text under it describes this whole section related to teamwork. You can either remove this or incorporate parts of it in the other `Team Work` sub-sections.

2021-03-04 03:04 UTC, noorbuchi commented on conduct.md
> +    * Share constructive criticism of others opinions before making a final decision as a group.
@corlettim  addressed this in the comment above so I will resolve mine

2021-03-04 03:16 UTC, enpuyou approved these changes

2021-03-04 03:17 UTC, noorbuchi approved these changes
Looks good!

2021-03-04 16:46 UTC, jjumadinova approved these changes

2021-03-04 17:00 UTC, merged